# Generated by Django 5.2.5 on 2025-09-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
